### PR TITLE
App error not handled

### PR DESCRIPTION
**Pull request by tonysnowboardunderthebridge**
Resolve https://github.com/platformatic/meraki/issues/691

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by marcopiraccini** [comment]
OK, but shouldn't we stop the spinner too @tonysnowboardunderthebridge ?

**Comment by tonysnowboardunderthebridge** [comment]
> OK, but shouldn't we stop the spinner too @tonysnowboardunderthebridge ?

You're right, I added the commit for avoid the infinite spinner

**Review by marcopiraccini — APPROVED** [review]
OK

**Pull request merged**
